//
//  XWCatergory.h
//  CatergoryDemo
//
//  Created by wazrx on 16/5/27.
//  Copyright © 2016年 wazrx. All rights reserved.
//

#import "XWCGUtilities.h"
#import "XWSingleton.h"
#import "XWCategoriesMacro.h"
#import "UIView+XWAddForFrame.h"
#import "UILabel+XWAddForFrame.h"
#import "CALayer+XWAddForFrame.h"
#import "Foundation+Log.m"
#import "CALayer+XWAdd.h"
#import "NSDate+XWAdd.h"
#import "NSData+XWAdd.h"
#import "NSString+XWAdd.h"
#import "NSNumber+XWAdd.h"
#import "NSArray+XWAdd.h"
#import "NSMutableArray+XWAdd.h"
#import "NSDictionary+XWAdd.h"
#import "NSMutableDictionary+XWAdd.h"
#import "NSNotificationCenter+XWAdd.h"
#import "NSTimer+XWAdd.h"
#import "NSObject+XWAdd.h"
#import "UIColor+XWAdd.h"
#import "UIImage+XWAdd.h"
#import "UIView+XWAdd.h"
#import "UIScreen+XWAdd.h"
#import "UIDevice+XWAdd.h"
#import "UIApplication+XWAdd.h"
#import "UIFont+XWAdd.h"
#import "UIBezierPath+XWAdd.h"
#import "UIScrollView+XWAdd.h"
#import "UITableView+XWAdd.h"
#import "UIActivityIndicatorView+XWAdd.h"
#import "UIAlertView+XWAdd.h"
#import "UIBarButtonItem+XWAdd.h"
#import "UIBarButtonItem+XWAdd.h"
#import "UICollectionViewFlowLayout+XWAdd.h"
#import "UIImageView+XWAdd.h"
#import "UILabel+XWAdd.h"
#import "UIControl+XWAdd.h"
#import "UIBarButtonItem+XWAdd.h"
#import "UINavigationController+XWAdd.h"
#import "UITextField+XWAdd.h"
